name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write  # Required for OIDC

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - id: release
        uses: google-github-actions/release-please-action@a02a34c4d625f9be7cb89156071d8dfe36043210 # v4.1.1
        with:
          release-type: python

      - if: ${{ steps.release.outputs.release_created }}
        name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - if: ${{ steps.release.outputs.release_created }}
        name: Install uv
        uses: astral-sh/setup-uv@1edb52594c857e2b5b13128931090f062282133b # v5.3.0

      - if: ${{ steps.release.outputs.release_created }}
        name: Build
        run: uv build

      - if: ${{ steps.release.outputs.release_created }}
        name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@67339c736fd9354e4f8d9f7a3d83413750308092 # release/v1
